---

- name: Be sure base packages are installed
  apt:
    autoremove: yes
    name:
      - ntp
      - git
      - software-properties-common
      - acl
      - vim
      - screen
      - openvpn
      - speedtest-cli
      - network-manager
      - network-manager-openvpn-gnome
      - openjdk-8-jre-headless
      - curl
      - mosquitto-clients
      - python3-pip
      - python3
    state: latest
    update_cache: yes
    cache_valid_time: 3600

# - name: Remove trashu applications
#   list:
#     - amazon
#     - aisleriot solitare
#     - cheese
#     - gnome mahjong
#     - gnome mines
#     - gnome power statictics
#     - gnome sudoku
#     - gnome-characters
#     - remmina
#     - rhythmbox
  

- name: Copy vim configuration
  copy:
    src: .vimrc
    dest: /etc/vimrc/