---

- name: Be sure base packages are installed
  apt:
    autoremove: yes
    name:
      - ntp
      - git
      - software-properties-common
      - acl
      - vim
      - screen
      - openvpn
      - speedtest-cli
      - network-manager
      - network-manager-openvpn-gnome
      - openjdk-8-jre-headless
      - curl
      - mosquitto-clients
      - python3-pip
      - python3.8
    state: latest
    update_cache: yes
    cache_valid_time: 3600

# - name: Remove some default apps
#   apt:
#     state: absent
#     name:
#       - aisleriot
#       - gnome-sudoku
#       - mahjongg
#       - ace-of-penguins
#       - gnomine
# apt remove aisleriot gnome-mahjongg gnome-mines gnome-sudoku 

  

- name: Copy vim configuration
  copy:
    src: .vimrc
    dest: /etc/vimrc/