---

- name: Terminal apps installed
  apt:
    name:
      - zsh
      - terminator
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: ZSH as default shell
  shell: "chsh -s /usr/bin/zsh {{ HOME.USER }}"

- name: Check default shell
  become_user: "{{ HOME.USER }}"
  shell: echo $SHELL
  register: shell_status

- name: INFO
  debug:
    msg: "Please restart computer"
  when: shell_status.stdout != "/usr/bin/zsh"

- name: Oh-my-zsh installed
  stat: 
    path: "{{ HOME.DIR }}/.oh-my-zsh"
  register: stat_result

- name: Oh-my-zsh framework installed
  become_user: "{{ HOME.USER }}"
  shell: "sh {{ role_path }}/files/install.sh"
  when: stat_result.stat.exists == False

- name: Create completion dir
  file:
    owner: "{{ HOME.USER }}"
    group: "{{ HOME.USER }}"
    path: "{{ HOME.DIR }}/.oh-my-zsh/completions"
    state: directory

- name: Download completion files
  get_url:
    url: https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/zsh/_docker-machine
    dest: "{{ HOME.DIR }}/.oh-my-zsh/completions/_docker-machine"


- name: Create terminator dir
  file:
    owner: "{{ HOME.USER }}"
    group: "{{ HOME.USER }}"
    path: "{{ HOME.DIR }}/.config/terminator"
    state: directory

- name: Terminal config in place
  copy:
    owner: "{{ HOME.USER }}"
    group: "{{ HOME.USER }}"
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: terminator.config
      dest: "{{ HOME.DIR }}/.config/terminator/config"
    - src: zshrc.config
      dest: "{{ HOME.DIR }}/.zshrc"

- name: User able to connect to usb
  shell: "usermod -a -G dialout {{ HOME.USER }}" 
