---

# - name: Install a .deb package from the internet.
#   apt:
#     deb: "https://update.code.visualstudio.com/{{ _VS_CODE.ver }}/linux-deb-x64/stable"

- name: Copy VS Code configuration
  copy:
    owner: "{{ HOME.USER }}"
    group: "{{ HOME.USER }}"
    src: "{{ item }}"
    dest: "{{ HOME.DIR }}/.config/Code/User"
  loop:
    - keybindings.json
    - pymakr.json
    - settings.json


- name: Install all extensions
  become_user: "{{ HOME.USER }}"
  shell: code --install-extension "{{ item }}"
  loop:
    - bungcip.better-toml
    - eamodio.gitlens
    - foxundermoon.shell-format
    - matangover.mypy
    - ms-azuretools.vscode-docker
    - ms-python.anaconda-extension-pack
    - ms-python.python
    - ms-vscode.cpptools
    # - ms-vscode.Go
    - pycom.pymakr
    - redhat.vscode-yaml
    - rust-lang.rust

- name: esptool installed
  pip:
    name: esptool
    executable: pip3




#https://code.visualstudio.com/docs/setup/linux