---

- name: Add Apt Keys
  apt_key: 
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 4773BD5E130D1D45
    state: present

- name: Add the Spotify repository
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    filename: "spotify"
    state: present
    update_cache: "yes"

- name: Spotify installed
  apt:
    update_cache: yes
    name:
    - spotify-client
    state: latest