---
- name: Install Docker's dependencies
  apt:
    name:
      - apt-transport-https=1.6.12
      - ca-certificates=20180409
      - gnupg2=2.2.4-1ubuntu1.2

- name: Add Docker's public PGP key to the APT keyring
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

- name: Configure Docker's upstream APT repository
  apt_repository:
    repo: >
      deb [arch=amd64]
      https://download.docker.com/linux/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    update_cache: true

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: remove docker-py
  pip:
    name: docker-py
    state: absent

- name: Install docker compose python module
  pip:
    name: docker-compose==1.12.0